import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";

const About: React.FC = () => {
  const router = useRouter();
  const name = "John Doe";

  const onLinkClick = () => {
    router.push({
      pathname: "/posts/[id]",
      query: { id: name },
    });
  };

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About</h1>
      <ul>
        <li>
          <Link href="/about">About</Link>
        </li>
        <li onClick={onLinkClick}>Posts by {name}</li>
      </ul>
    </>
  );
};

export default About;
