import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";

const Home: React.FC = () => {
  const router = useRouter();
  const name = "Homely Person";

  const onLinkClick = () => {
    router.push({
      pathname: "/posts/[id]",
      query: { id: name },
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home</h1>
      <ul>
        <li>
          <Link href="/about">About</Link>
        </li>
        <li>
          <Link
            href={{
              pathname: "/posts/[id]",
              query: { id: name },
            }}
          >
            Posts by {name}
          </Link>
        </li>
      </ul>
    </>
  );
};

export default Home;
