import Head from "next/head";
import Link from "next/link";
import React from "react";

interface IProps {
  apiData: any;
}

const Posts: React.FC<IProps> = ({ apiData }) => {
  const { id } = apiData;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Post: {id}</h1>
      <ul>
        <li>
          <Link href="/about">About</Link>
        </li>
        <li>
          <Link href="/">Home</Link>
        </li>
      </ul>
    </>
  );
};

export default Posts;
